node {
    stage('Checkout') {
        git url: 'https://github.com/Rydor/HA.git'
    }
    stage('Test') {
        sh 'python ./test_disruptor.py'
    }
    stage('Deploy') {
        echo 'Deploying....'
    }
}
