node {
    stage('Checkout') {
        git url: 'https://github.com/Rydor/HA'
    }
    stage('Test') {
        sh ./test_disruptor.py
    }
    stage('Deploy') {
        echo 'Deploying....'
    }
}
