node {
    stage('Checkout') {
        git url: 'https://github.com/Rydor/HA.git'
    }
    stage('Setup') {
        sh '. /opt/jenkins/bin/activate'
        sh 'pip install --trusted-host pypi.python.org -r requirements.txt'
    }
    stage('Test') {
        sh 'python ./test_disruptor.py'
    }
    stage('Deploy') {
        echo 'Deploying....'
    }
}
